model_type: dofa
size: base
num_classes: 10
task: classification
band_wavelengths: null
freeze_backbone: true
image_resolution: 224
additional_params: {}
multilabel: false
out_features: true
embed_dim: 768
pretrained_path: ${oc.env:MODEL_WEIGHTS_DIR}/DOFA_ViT_${size}_e100.pth
full_finetune: false