defaults:
  - base_model

model_type: croma
task: classification
size: base
modality: optical
image_resolution: 120
pretrained_path: ${oc.env:MODEL_WEIGHTS_DIR}/CROMA_${size}.pt
num_channels: 12
freeze_backbone: False
out_features: True

