defaults:
  - base_model

model_type: croma
task: segmentation
size: base
modality: optical
image_resolution: 120
embed_dim: 768
pretrained_path: ${oc.env:MODEL_WEIGHTS_DIR}/CROMA_${size}.pt
num_channels: 12

