defaults:
  - base_model

model_type: dinov2
task: classification
dino_size: dinov2_vitl14
image_resolution: 224
embed_dim: 1024
pretrained_path: null  # Add path if required
num_channels: 3
lora: true
lora_target_modules:
  - qkv
  - proj
