defaults:
  - base_model_dofa

task: classification
lora: false
full_finetune: false
trainable_params:
  - patch_embed.fclayer.w1.weight
  - patch_embed.fclayer.w1.bias
  - patch_embed.fclayer.w2.weight
  - patch_embed.fclayer.w2.bias
