defaults:
  - base_model

model_type: gfm
task: classification
image_resolution: 192
embed_dim: 1024
pretrained_path: ${oc.env:MODEL_WEIGHTS_DIR}/gfm.pth
num_channels: 3
full_finetune: false
trainable_params:
  - patch_embed.proj.weight
  - patch_embed.proj.bias
  - patch_embed.norm.weight
  - patch_embed.norm.bias

