defaults:
  - base_model

model_type: scalemae
task: classification
image_resolution: 224
embed_dim: 1024
pretrained_path: ${oc.env:MODEL_WEIGHTS_DIR}/scalemae-vitlarge-800.pth
num_channels: 3
trainable_params:
  - patch_embed.proj.weight
  - patch_embed.proj.bias

