defaults:
  - base_dataset

dataset_type: benv2
task: classification
dataset_name: benv2
num_classes: 19
num_channels: 14
data_path: ${oc.env:DATASETS_DIR}/benv2
image_resolution: 224  # Desired image size for model input
multilabel: true
bands: all  # Argument for torchgeo loader
download: True

