defaults:
  - geobench

benchmark_name: segmentation_v1.0
dataset_name: m-pv4ger-seg
task: segmentation
band_names:
  - "Blue"
  - "Green"
  - "Red"
band_wavelengths:
  - 0.48
  - 0.56
  - 0.66
num_classes: 2
multilabel: false
num_channels: 3

