defaults:
  - geobench

benchmark_name: classification_v1.0
dataset_name: m-forestnet
task: classification
band_names:
  - "02 - Blue"
  - "03 - Green"
  - "04 - Red"
num_classes: 12
multilabel: false
num_channels: 3

