defaults:
  - geobench_sacrop

band_names:
  - "01 - Coastal aerosol"
  - "02 - Blue"
  - "03 - Green"
  - "04 - Red"
  - "05 - Vegetation Red Edge"
  - "06 - Vegetation Red Edge"
  - "07 - Vegetation Red Edge"
  - "08 - NIR"
  - "08A - Vegetation Red Edge"
  - "09 - Water vapour"
  - "09 - Water vapour"
  - "12 - SWIR"
num_channels: 12

