defaults:
  - base_dataset

dataset_type: resisc45
task: classification
dataset_name: resisc45
num_classes: 45
num_channels: 3
data_path: ${oc.env:DATASETS_DIR}/resisc45
band_names: ["Red", "Green", "Blue"]
image_resolution: 224
multilabel: false

