defaults:
  - base_dataset

dataset_type: tropical_cyclone
task: regression
dataset_name: tropical_cyclone
num_classes: 1
num_channels: 3
data_path: ${oc.env:DATASETS_DIR}/TropicalCyclone
image_resolution: 224
band_wavelengths: [11, 11, 11] # 
multilabel: false